---

sudo: required

language: bash

services:
  - docker

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_install:
  - sudo apt-get install realpath
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

script:
  - tests/style
  - bats tests/functional

after_success:
  - >
    [ -n "$TRAVIS_TAG" ]
    && curl -X POST -H "Content-Type: application/json"
    --data "{\"source_type\": \"Tag\", \"source_name\": \"$TRAVIS_TAG\"}"
    https://registry.hub.docker.com/u/grpn/ansible-silo/trigger/$DOCKER_HUB_TOKEN/

...
