---

sudo: required

language: ruby

rvm: 2.4.1

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - bats
      - bc

before_script:
  - scversion="stable"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
  - gem install awesome_bot
  - npm install -g dockerfilelint
  - sudo add-apt-repository ppa:duggan/bats --yes
  - >-
    sudo apt-get install -qq realpath \
                             make
  - ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

script:
  - make test-style
  - make test-links
  - make test-function

after_success:
  - >
    [ -n "$TRAVIS_TAG" ]
    && curl -X POST -H "Content-Type: application/json"
    --data "{\"source_type\": \"Tag\", \"source_name\": \"$TRAVIS_TAG\"}"
    https://registry.hub.docker.com/u/grpn/ansible-silo/trigger/$DOCKER_HUB_TOKEN/

...
